name: Beeminder
on:
  push:
    branches:
      - main
jobs:
  bm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Count changes
        run: |
          git show --oneline
          echo "COUNT=$(git show --oneline | wc -m | xargs)" >> $GITHUB_ENV
      - name: Post to Beeminder
        run: |
          curl -X POST https://www.beeminder.com/api/v1/users/${{ secrets.BEEMINDER_USERNAME }}/goals/tr-theory/datapoints.json \
            -d auth_token=${{ secrets.BEEMINDER_AUTH_TOKEN }} \
            -d requestid=${{ github.sha }} \
            -d value=${{ env.COUNT }} \
            -d comment="${{ github.event.head_commit.message }} (${{ github.repository }}:${{ github.sha }})"
